POPULATION_SIZE = 40
INDIVIDUAL_SIZE = 40
NUMBER_OF_ITERATIONS = 5
NUMBER_OF_RUNS = 30
NUMBER_OF_INDIVIDUALS_FOR_PARENTS_SELECTION = 2
SIZE_OF_TOURNAMENT = 5
NUMBER_OF_INDIVIDUALS_FOR_SURVIVORS_SELECTION = POPULATION_SIZE
GENE_MUTATION_PROBABILITY = 0.33
STARTING_COORDS_X = 14
STARTING_COORDS_Y = 8

