POPULATION_SIZE = 150
INDIVIDUAL_SIZE = 25
NUMBER_OF_ITERATIONS = 30
NUMBER_OF_RUNS = 1
NUMBER_OF_INDIVIDUALS_FOR_PARENTS_SELECTION = 2
SIZE_OF_TOURNAMENT = 2
NUMBER_OF_INDIVIDUALS_FOR_SURVIVORS_SELECTION = POPULATION_SIZE
GENE_MUTATION_PROBABILITY = 0.33
STARTING_COORDS_X = 14
STARTING_COORDS_Y = 8

